/*
 * generated by Xtext
 */
package hu.bme.mit.inf.gomrp.statemachine.dsl.text;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class StateMachineDSLRuntimeModule extends hu.bme.mit.inf.gomrp.statemachine.dsl.text.AbstractStateMachineDSLRuntimeModule {

}
