/*
* generated by Xtext
*/
package hu.bme.mit.inf.gomrp.statemachine.dsl.text;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class StateMachineDSLStandaloneSetup extends StateMachineDSLStandaloneSetupGenerated{

	public static void doSetup() {
		new StateMachineDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

