/*
 * generated by Xtext
 */
package hu.bme.mit.inf.gomrp.statemachine.dsl.text.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class StateMachineDSLUiModule extends hu.bme.mit.inf.gomrp.statemachine.dsl.text.ui.AbstractStateMachineDSLUiModule {
	public StateMachineDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
