/*
 * generated by Xtext
 */
package hu.bme.mit.inf.gomrp.railway.dsl.ui.contentassist

import hu.bme.mit.inf.gomrp.railway.dsl.ui.contentassist.AbstractRDMTextDSLProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class RDMTextDSLProposalProvider extends AbstractRDMTextDSLProposalProvider {
}
