/*
* generated by Xtext
*/
package hu.bme.mit.inf.gomrp.railway.dsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import hu.bme.mit.inf.gomrp.railway.dsl.services.RDMTextDSLGrammarAccess;

public class RDMTextDSLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private RDMTextDSLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected hu.bme.mit.inf.gomrp.railway.dsl.parser.antlr.internal.InternalRDMTextDSLParser createParser(XtextTokenStream stream) {
		return new hu.bme.mit.inf.gomrp.railway.dsl.parser.antlr.internal.InternalRDMTextDSLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "RailwayDomainModel";
	}
	
	public RDMTextDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(RDMTextDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
