/*
* generated by Xtext
*/
package hu.bme.mit.inf.gomrp.railway.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class RDMTextDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("hu/bme/mit/inf/gomrp/railway/dsl/parser/antlr/internal/InternalRDMTextDSL.tokens");
	}
}
