/*
 * generated by Xtext
 */
package hu.bme.mit.inf.gomrp.statemachine.dsl.text.ui.contentassist

import hu.bme.mit.inf.gomrp.statemachine.dsl.text.ui.contentassist.AbstractStateMachineDSLProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class StateMachineDSLProposalProvider extends AbstractStateMachineDSLProposalProvider {
}
