/*
* generated by Xtext
*/
package hu.bme.mit.inf.gomrp.statemachine.dsl.text.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import hu.bme.mit.inf.gomrp.statemachine.dsl.text.services.StateMachineDSLGrammarAccess;

public class StateMachineDSLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private StateMachineDSLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected hu.bme.mit.inf.gomrp.statemachine.dsl.text.parser.antlr.internal.InternalStateMachineDSLParser createParser(XtextTokenStream stream) {
		return new hu.bme.mit.inf.gomrp.statemachine.dsl.text.parser.antlr.internal.InternalStateMachineDSLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "StateMachineBehavioralModel";
	}
	
	public StateMachineDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(StateMachineDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
