/*
* generated by Xtext
*/
package hu.bme.mit.inf.gomrp.statemachine.dsl.text.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class StateMachineDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("hu/bme/mit/inf/gomrp/statemachine/dsl/text/parser/antlr/internal/InternalStateMachineDSL.tokens");
	}
}
