/*
 * generated by Xtext
 */
package hu.bme.mit.inf.gomrp.statemachine.dsl.text.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import hu.bme.mit.inf.gomrp.statemachine.dsl.text.ui.internal.StateMachineDSLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class StateMachineDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return StateMachineDSLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return StateMachineDSLActivator.getInstance().getInjector(StateMachineDSLActivator.HU_BME_MIT_INF_GOMRP_STATEMACHINE_DSL_TEXT_STATEMACHINEDSL);
	}
	
}
