/*
 * generated by Xtext
 */
package hu.bme.mit.inf.gomrp.railway.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RDMTextDSLRuntimeModule extends hu.bme.mit.inf.gomrp.railway.dsl.AbstractRDMTextDSLRuntimeModule {

}
