/*
 * generated by Xtext
 */
package hu.bme.mit.inf.gomrp.railway.dsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractRDMTextDSLValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(EPackage.Registry.INSTANCE.getEPackage("hu.bme.mit.inf.gomrp.railway"));
		return result;
	}
}
