/*
 * generated by Xtext
 */
package hu.bme.mit.inf.gomrp.railway.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class RDMTextDSLUiModule extends hu.bme.mit.inf.gomrp.railway.dsl.ui.AbstractRDMTextDSLUiModule {
	public RDMTextDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
