/*
 * generated by Xtext
 */
package hu.bme.mit.inf.gomrp.railway.dsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import hu.bme.mit.inf.gomrp.railway.dsl.ui.internal.RDMTextDSLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RDMTextDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return RDMTextDSLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return RDMTextDSLActivator.getInstance().getInjector(RDMTextDSLActivator.HU_BME_MIT_INF_GOMRP_RAILWAY_DSL_RDMTEXTDSL);
	}
	
}
